# Generated by Django 2.1.3 on 2018-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.IntegerField(db_index=True)),
                ('contest_id', models.IntegerField(db_index=True)),
                ('judge_id', models.IntegerField(db_index=True, default=-1)),
                ('grade', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ContestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.IntegerField(db_index=True)),
                ('member1_id', models.IntegerField(db_index=True, null=True)),
                ('member2_id', models.IntegerField(db_index=True, null=True)),
                ('member3_id', models.IntegerField(db_index=True, null=True)),
                ('member4_id', models.IntegerField(db_index=True, null=True)),
                ('contest_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(db_index=True)),
                ('contest_id', models.IntegerField(db_index=True)),
                ('extra_information', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.AddField(
            model_name='contest',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
