# Generated by Django 2.1.3 on 2018-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20181113_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccpuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='contest',
            name='brief_introduction',
            field=models.CharField(default='empty', max_length=128),
            preserve_default=False,
        ),
    ]
