# Generated by Django 2.1.3 on 2018-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_contestplayer_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestjudge',
            name='phase_region1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestjudge',
            name='phase_region2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestjudge',
            name='phase_region3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestjudge',
            name='phase_region4',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestjudge',
            name='phase_region5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestplayer',
            name='phase_region1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestplayer',
            name='phase_region2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestplayer',
            name='phase_region3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestplayer',
            name='phase_region4',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contestplayer',
            name='phase_region5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
