# Generated by Django 2.1.3 on 2018-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20181203_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='phase_region_mode1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase_region_mode2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase_region_mode3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase_region_mode4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase_region_mode5',
            field=models.IntegerField(default=0),
        ),
    ]
