# Generated by Django 2.1.3 on 2018-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20181203_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('brief_introduction', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'HotContest',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author_id', models.IntegerField(db_index=True)),
                ('author', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=1024)),
                ('time', models.DateTimeField()),
                ('replies', models.IntegerField(default=0)),
                ('last_reply_time', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(db_index=True)),
                ('author_id', models.IntegerField(db_index=True)),
                ('content', models.CharField(max_length=1024)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Reply',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Slider',
            },
        ),
        migrations.RemoveField(
            model_name='notificationuser',
            name='time',
        ),
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
